services:
  - type: web
    name: income-predictor
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
git add render.yaml
git commit -m "Add .render.yaml for deployment"
git push
